// src/app/projects/projects.data.ts

export interface Project {
  title: string;
  description: string;
  image: string;
  github: string;
  video: string;
  link: string;
  download: string;
  images: string[];
}

export const PROJECTS: Project[] = [
        {
        title: 'projects.fullstack',
        description: 'projects.fullstackdesc',
        image: '/assets/images/projects/ls.png',
        github: '',
        video: 'https://www.youtube.com/@livesenorita',
        link: 'https://livesenorita.com',
        download: '',
        images: [
          'assets/images/projects/ls.png',
          'assets/images/projects/livesenor/livesenor_1.png',
          'assets/images/projects/livesenor/livesenor_2.png',
          'assets/images/projects/livesenor/livesenor_3.png',
          'assets/images/projects/livesenor/livesenor_4.png',
          'assets/images/projects/livesenor/livesenor_5.png'
    ],
      },
      {
        title: 'projects.port',
        description: 'projects.portDesc',
        image: '/assets/images/projects/art.png',
        github: 'https://github.com/borsosbalazselek/Portfolio',
        video: '',
        link: 'https://www.autorobottech.hu',
        download: '',
        images: [
          'assets/images/projects/art.png'
    ],
      },
      {
        title: 'projects.nml',
        description: 'projects.nmldesc',
        image: '/assets/images/projects/NML.jpg',
        github: '',
        video: 'https://www.youtube.com/watch?v=WPUukeF-1zo',
        link: 'https://store.steampowered.com/app/1363400/No_More_Light/',
        download: '',
        images: [
          'assets/images/projects/NML.jpg',
          'assets/images/projects/NML/NML_1.jpg',
          'assets/images/projects/NML/NML_2.jpg',
          'assets/images/projects/NML/NML_3.jpg',
          'assets/images/projects/NML/NML_4.jpg',
          'assets/images/projects/NML/NML_5.jpg',
          'assets/images/projects/NML/NML_6.jpg'
    ],
      },
      {
        title: 'projects.sac',
        description: 'projects.sacDesc',
        image: '/assets/images/projects/sac.png',
        github: '',
        video: '',
        link: '',
        download: '',
        images: [
          'assets/images/projects/sac/sac_9.png',
          'assets/images/projects/sac/sac_8.png',
          'assets/images/projects/sac/sac_7.png',
          'assets/images/projects/sac/sac_6.png',
          'assets/images/projects/sac/sac_5.png',
          'assets/images/projects/sac/sac_4.png',
          'assets/images/projects/sac/sac_3.png',
          'assets/images/projects/sac/sac_2.png',
          'assets/images/projects/sac/sac_1.png'
    ],
      },
      {
        title: 'projects.mud',
        description: 'projects.mudtext',
        image: '/assets/images/projects/mud.jpg',
        github: '',
        video: '',
        link: '',
        download: '',
        images: [
          'assets/images/projects/MUDFEST/MUD_1.jpg',
          'assets/images/projects/MUDFEST/MUD_2.jpg',
          'assets/images/projects/MUDFEST/MUD_3.jpg',
          'assets/images/projects/MUDFEST/MUD_4.jpg',
          'assets/images/projects/MUDFEST/MUD_5.jpg',
          'assets/images/projects/MUDFEST/MUD_6.jpg',
          'assets/images/projects/MUDFEST/MUD_7.jpg',
          'assets/images/projects/MUDFEST/MUD_8.jpg',
          'assets/images/projects/MUDFEST/MUD_9.jpg',
    ],
      },
      {
        title: 'projects.simoreg',
        description: 'projects.simoregDesc',
        image: '/assets/images/projects/simoreg.jpg',
        github: '',
        video: '',
        link: '',
        download: '',
        images: [
          'assets/images/projects/simoreg/simoreg_1.jpg',
          'assets/images/projects/simoreg/simoreg_2.jpg',
          'assets/images/projects/simoreg/simoreg_3.jpg',
          'assets/images/projects/simoreg/simoreg_4.jpg',
          'assets/images/projects/simoreg/simoreg_5.jpg',
          'assets/images/projects/simoreg/simoreg_6.jpg',
          'assets/images/projects/simoreg/simoreg_7.jpg',
          'assets/images/projects/simoreg/simoreg_8.jpg'
    ],
      },      
      {
        title: 'projects.humrob',
        description: 'projects.humrobtext',
        image: '/assets/images/projects/robo.jpg',
        github: 'https://github.com/borsosbalazselek/MotorDriver_controll.git',
        video: 'https://www.youtube.com/shorts/H2qO61vyajk',
        link: '',
        download: '',
        images: [
          'assets/images/projects/robo/robo_01.jpg',
          'assets/images/projects/robo/robo_02.jpg',
          'assets/images/projects/robo/robo_03.jpg',
          'assets/images/projects/robo/robo_04.jpg',
          'assets/images/projects/robo/robo_05.jpg',
          'assets/images/projects/robo/robo_06.jpg',
          'assets/images/projects/robo/robo_07.jpg',
          'assets/images/projects/robo/robo_08.jpg',
          'assets/images/projects/robo/robo_09.jpg',
          'assets/images/projects/robo/robo_10.jpg',
          'assets/images/projects/robo/robo_11.jpg',
          'assets/images/projects/robo/robo_12.jpg',
          'assets/images/projects/robo/robo_13.jpg',
          'assets/images/projects/robo/robo_14.jpg',
          'assets/images/projects/robo/robo_15.jpg',
          'assets/images/projects/robo/robo_16.jpg',
          'assets/images/projects/robo/robo_17.jpg',
          'assets/images/projects/robo/robo_18.jpg',
          'assets/images/projects/robo/robo_19.jpg',
          'assets/images/projects/robo/robo_20.jpg',
          'assets/images/projects/robo/robo_21.jpg',
          'assets/images/projects/robo/robo_22.jpg',
          'assets/images/projects/robo/robo_23.jpg',
          'assets/images/projects/robo/robo_24.jpg',
          'assets/images/projects/robo/robo_25.jpg',
          'assets/images/projects/robo/robo_26.jpg',
          'assets/images/projects/robo/robo_27.jpg'

    ],
      },
      {
        title: 'projects.fpga',
        description: 'projects.fpgatext',
        image: '/assets/images/projects/nexys.png',
        github: 'https://github.com/borsosbalazselek/Traffic_Lights_Hex-Vga.git',
        video: '',
        link: '',
        download: '',
        images: [
          '/assets/images/projects/nexys.png'
    ],
      },
      {
        title: 'projects.pynq',
        description: 'projects.pynqtext',
        image: '/assets/images/projects/pynq.png',
        github: 'https://github.com/borsosbalazselek/face_Servo.git',
        video: 'https://www.youtube.com/shorts/U6Ev3lqUo1k',
        link: '',
        download: '',
        images: [
          'assets/images/projects/pynq/pynq_0.png',
          'assets/images/projects/pynq/pynq_1.jpg',
          'assets/images/projects/pynq/pynq_2.jpg',
          'assets/images/projects/pynq/pynq_3.jpg',
          'assets/images/projects/pynq/pynq_4.jpg',
          'assets/images/projects/pynq/pynq_5.jpg',
          'assets/images/projects/pynq/pynq_6.jpg',
          'assets/images/projects/pynq/pynq_7.jpg',
          'assets/images/projects/pynq/pynq_8.jpg',
          'assets/images/projects/pynq/pynq_9.jpg',
          'assets/images/projects/pynq/pynq_10.jpg',
          'assets/images/projects/pynq/pynq_11.jpg'
    ],
      },
      {
        title: 'projects.autocar',
        description: 'projects.autocarDesc',
        image: '/assets/images/projects/autocar.jpg',
        github: '',
        video: '',
        link: '',
        download: '',
        images: [
          'assets/images/projects/autocar/autocar_1.jpg',
          'assets/images/projects/autocar/autocar_2.jpg',
          'assets/images/projects/autocar/autocar_3.jpg',
          'assets/images/projects/autocar/autocar_4.jpg',
          'assets/images/projects/autocar/autocar_5.jpg',
          'assets/images/projects/autocar/autocar_6.jpg'
    ],
      },
      {
        title: 'projects.elektrash',
        description: 'projects.elektrashDesc',
        image: '/assets/images/projects/elektrash.jpg',
        github: '',
        video: '',
        link: '',
        download: '',
        images: [
          'assets/images/projects/elektrash/elektracs_1.jpg',
          'assets/images/projects/elektrash/elektracs_2.jpg',
          'assets/images/projects/elektrash/elektracs_3.jpg',
          'assets/images/projects/elektrash/elektracs_4.jpg',
          'assets/images/projects/elektrash/elektracs_5.jpg',
          'assets/images/projects/elektrash/elektracs_6.jpg',
          'assets/images/projects/elektrash/elektracs_7.jpg'
    ],
      },
      {
        title: 'projects.laserengrav',
        description: 'projects.laserengravDesc',
        image: '/assets/images/projects/laserengrav.jpg',
        github: '',
        video: '',
        link: '',
        download: '',
        images: [
          'assets/images/projects/laserengrav/laserengrav_01.jpg',
          'assets/images/projects/laserengrav/laserengrav_02.jpg',
          'assets/images/projects/laserengrav/laserengrav_03.jpg'
    ],
      },
      {
        title: 'projects.malta',
        description: 'projects.maltaDesc',
        image: '/assets/images/projects/malta.jpg',
        github: 'https://github.com/borsosbalazselek/SSVP_Sensor_serial.git',
        video: '',
        link: '',
        download: '',
        images: [
          'assets/images/projects/malta/malta_1.jpg',
          'assets/images/projects/malta/malta_2.jpg',
          'assets/images/projects/malta/malta_3.jpg'
    ],
      },
      {
        title: 'projects.netlock',
        description: 'projects.netlockDesc',
        image: '/assets/images/projects/netlock.jpg',
        github: 'https://github.com/borsosbalazselek/Door_Control_Lock.git',
        video: '',
        link: '',
        download: '',
        images: [
          'assets/images/projects/netlock/netlock_1.jpg',
          'assets/images/projects/netlock/netlock_2.jpg',
          'assets/images/projects/netlock/netlock_3.jpg',
          'assets/images/projects/netlock/netlock_4.jpg',
          'assets/images/projects/netlock/netlock_5.jpg'
    ],
      },
      {
        title: 'projects.tdprint',
        description: 'projects.tdprintDesc',
        image: '/assets/images/projects/tdp.png',
        github: '',
        video: '',
        link: 'https://www.tinkercad.com/users/2uO5kMx6A12-lex333',
        download: '',
        images: [
          'assets/images/projects/tdprint/tdp_00.png',
          'assets/images/projects/tdprint/tdp_01.png',
          'assets/images/projects/tdprint/tdp_02.png',
          'assets/images/projects/tdprint/tdp_03.jpg',
          'assets/images/projects/tdprint/tdp_04.jpg',
          'assets/images/projects/tdprint/tdp_05.jpg',
          'assets/images/projects/tdprint/tdp_06.jpg',
          'assets/images/projects/tdprint/tdp_07.jpg',
    ],
      },
      {
        title: 'projects.unity',
        description: 'projects.unityDesc',
        image: '/assets/images/projects/unity.png',
        github: '',
        video: '',
        link: '',
        download: '',
        images: [
          'assets/images/projects/unity/unity.png'
        ],
      },
      {
        title: 'projects.inertia',
        description: 'projects.inertiaDesc',
        image: '/assets/images/projects/inertia.png',
        github: 'https://github.com/borsosbalazselek/Inertia',
        video: '',
        link: '',
        download: 'https://www.autorobottech.hu/downloads/Inertia.zip',
        images: [
          'assets/images/projects/inertia/inertia_01.png',
          'assets/images/projects/inertia/inertia_02.png',
          'assets/images/projects/inertia/inertia_03.png',
          'assets/images/projects/inertia/inertia_04.png'
        ],
      },
      {
        title: 'projects.clobber',
        description: 'projects.clobberDesc',
        image: '/assets/images/projects/clobber.png',
        github: 'https://github.com/borsosbalazselek/Clobber.git',
        video: '',
        link: '',
        download: 'https://www.autorobottech.hu/downloads/Clobber.zip',
        images: [
          'assets/images/projects/clobber/clobber_01.png',
          'assets/images/projects/clobber/clobber_02.png',
          'assets/images/projects/clobber/clobber_03.png',
          'assets/images/projects/clobber/clobber_04.png'
        ],
      },
      {
        title: 'projects.selfbalance',
        description: 'projects.selfbalanceDesc',
        image: '/assets/images/projects/selfbalance.jpg',
        github: 'https://github.com/borsosbalazselek/SelfBalance_Robot.git',
        video: 'https://www.youtube.com/watch?v=x6nGQ3k16VU',
        link: '',
        download: '',
        images: [
          'assets/images/projects/selfbalance/selfbalance_1.jpg',
          'assets/images/projects/selfbalance/selfbalance_2.jpg'
        ],
      },
      {
        title: 'projects.ITS',
        description: 'projects.ITSDesc',
        image: '/assets/images/projects/ITS.png',
        github: '',
        video: '',
        link: '',
        download: 'https://www.autorobottech.hu/downloads/BENTLEY.pptx',
        images: [
          'assets/images/projects/ITS/ITS_0.png',
          'assets/images/projects/ITS/ITS_1.png',
          'assets/images/projects/ITS/ITS_2.png',
          'assets/images/projects/ITS/ITS_3.png',
          'assets/images/projects/ITS/ITS_4.png'
        ],
      },
      {
        title: 'projects.pg_mm',
        description: 'projects.pg_mmDesc',
        image: '/assets/images/projects/pg_mm.jpg',
        github: '',
        video: '',
        link: '',
        download: '',
        images: [
          'assets/images/projects/pg_mm/pg_mm_01.jpg',
          'assets/images/projects/pg_mm/pg_mm_02.jpg',
          'assets/images/projects/pg_mm/pg_mm_03.jpg',
          'assets/images/projects/pg_mm/pg_mm_04.jpg',
          'assets/images/projects/pg_mm/pg_mm_05.jpg',
          'assets/images/projects/pg_mm/pg_mm_06.jpg',
          'assets/images/projects/pg_mm/pg_mm_07.jpg',
          'assets/images/projects/pg_mm/pg_mm_08.jpg',
          'assets/images/projects/pg_mm/pg_mm_09.jpg',
          'assets/images/projects/pg_mm/pg_mm_10.jpg',
          'assets/images/projects/pg_mm/pg_mm_11.jpg',
          'assets/images/projects/pg_mm/pg_mm_12.jpg',
          'assets/images/projects/pg_mm/pg_mm_13.jpg',
          'assets/images/projects/pg_mm/pg_mm_14.jpg',
          'assets/images/projects/pg_mm/pg_mm_15.jpg',
          'assets/images/projects/pg_mm/pg_mm_16.jpg',
          'assets/images/projects/pg_mm/pg_mm_17.jpg',
          'assets/images/projects/pg_mm/pg_mm_18.jpg',
          'assets/images/projects/pg_mm/pg_mm_19.jpg',
          'assets/images/projects/pg_mm/pg_mm_20.png'
        ],
      },
      {
        title: 'projects.pg_lt',
        description: 'projects.pg_ltDesc',
        image: '/assets/images/projects/pg_lt.png',
        github: '',
        video: '',
        link: '',
        download: 'https://www.autorobottech.hu/downloads/render.rar',
        images: [
          'assets/images/projects/pg_lt/pg_lt_01.png',
          'assets/images/projects/pg_lt/pg_lt_02.png',
          'assets/images/projects/pg_lt/pg_lt_03.png',
          'assets/images/projects/pg_lt/pg_lt_04.jpg',
          'assets/images/projects/pg_lt/pg_lt_05.jpg'
        ],
      },
      {
        title: 'projects.bellcont',
        description: 'projects.bellcontDesc',
        image: '/assets/images/projects/bellcont.png',
        github: 'https://github.com/borsosbalazselek/Bell_Control_Desktop.git',
        video: '',
        link: '',
        download: '',
        images: [
          'assets/images/projects/bellcont/bell_01.jpg',
          'assets/images/projects/bellcont/bell_02.jpg',
          'assets/images/projects/bellcont/bell_03.jpg',
          'assets/images/projects/bellcont/bell_04.png'
        ],
      },
      {
        title: 'projects.sms',
        description: 'projects.smsDesc',
        image: '/assets/images/projects/sms.png',
        github: 'https://github.com/borsosbalazselek/sms_handler.git',
        video: '',
        link: '',
        download: '',
        images: [
          'assets/images/projects/sms/sms_01.png',
          'assets/images/projects/sms/sms_02.png'
        ],
      },
      {
        title: 'projects.checkin',
        description: 'projects.checkinDesc',
        image: '/assets/images/projects/checkin.jpg',
        github: 'https://github.com/borsosbalazselek/Check_Button.git',
        video: '',
        link: '',
        download: '',
        images: [
          'assets/images/projects/checkin/checkin_1.jpg',
          'assets/images/projects/checkin/checkin_2.jpg',
          'assets/images/projects/checkin/checkin_3.jpg',
          'assets/images/projects/checkin/checkin_4.jpg',
          'assets/images/projects/checkin/checkin_5.jpg',
          'assets/images/projects/checkin/checkin_6.jpg',
          'assets/images/projects/checkin/checkin_7.jpg',
          'assets/images/projects/checkin/checkin_8.jpg',
          'assets/images/projects/checkin/checkin_0.jpg'
        ],
      },
      {
        title: 'projects.tbc',
        description: 'projects.tbcDesc',
        image: '/assets/images/projects/tbc.jpg',
        github: 'https://github.com/borsosbalazselek/Tower_BellControl_arduino.git',
        video: '',
        link: '',
        download: 'https://www.autorobottech.hu/downloads/BC100_manual.pdf',
        images: [
          '/assets/images/projects/tbc/tbc_01.jpg',
          '/assets/images/projects/tbc/tbc_02.jpg',
          '/assets/images/projects/tbc/tbc_03.jpg',
          '/assets/images/projects/tbc/tbc_04.jpg',
          '/assets/images/projects/tbc/tbc_05.jpg',
          '/assets/images/projects/tbc/tbc_06.jpg',
          '/assets/images/projects/tbc/tbc_07.jpg',
          '/assets/images/projects/tbc/tbc_08.jpg',
          '/assets/images/projects/tbc/tbc_09.jpg',
          '/assets/images/projects/tbc/tbc_10.jpg',
          '/assets/images/projects/tbc/tbc_11.jpg',
        ],
      },
      {
        title: 'projects.hivecont',
        description: 'projects.hivecontDesc',
        image: '/assets/images/projects/hivecont.jpg',
        github: 'https://github.com/borsosbalazselek/Hive_Control.git',
        video: '',
        link: '',
        download: '',
        images: [
          '/assets/images/projects/hivecont/hc_01.jpg',
          '/assets/images/projects/hivecont/hc_02.jpg',
          '/assets/images/projects/hivecont/hc_03.jpg',
          '/assets/images/projects/hivecont/hc_04.jpg',
          '/assets/images/projects/hivecont/hc_05.jpg',
          '/assets/images/projects/hivecont/hc_06.jpg',
          '/assets/images/projects/hivecont/hc_07.jpg',
          '/assets/images/projects/hivecont/hc_08.jpg',
          '/assets/images/projects/hivecont/hc_09.jpg'
        ],
      },
      {
        title: 'projects.projectt',
        description: 'projects.projecttDesc',
        image: '/assets/images/projects/projectt.jpg',
        github: '',
        video: '',
        link: 'https://en.wikipedia.org/wiki/Project_Torque',
        download: '',
        images: [
          '/assets/images/projects/projectt/pt_01.jpg',
          '/assets/images/projects/projectt/pt_02.jpg',
          '/assets/images/projects/projectt/pt_03.jpg',
          '/assets/images/projects/projectt/pt_04.jpg',
          '/assets/images/projects/projectt/pt_05.jpg',
          '/assets/images/projects/projectt/pt_06.jpg'
        ],
      },
      {
        title: 'projects.monsterg',
        description: 'projects.monstergDesc',
        image: '/assets/images/projects/monsterg.jpg',
        github: '',
        video: '',
        link: 'https://en.wikipedia.org/wiki/Monster_Garage_(video_game)',
        download: '',
        images: [
          '/assets/images/projects/monsterg/mg_01.jpg',
          '/assets/images/projects/monsterg/mg_02.jpg',
          '/assets/images/projects/monsterg/mg_03.png',
          '/assets/images/projects/monsterg/mg_04.jpg'
        ],
      },
      {
        title: 'projects.login',
        description: 'projects.loginDesc',
        image: '/assets/images/projects/login.png',
        github: '',
        video: '',
        link: '',
        download: '',
        images: [
          '/assets/images/projects/login/login_01.jpg',
          '/assets/images/projects/login/login_02.jpg',
          '/assets/images/projects/login/login_03.jpg'
        ],
      }
  
];


